[package]
name = "chord_map_egui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
note_lib = { path = "../note_lib" }
egui = "0.24.1"
strum = "0.25.0"
